### ISSUE TITLE
Improve the Japanese font stack

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#78]
Determine a **web-safe font stack supporting all devices** (OS X/iOS, Windows, Linux, Android).

Cf [The ultimate JAPANESE serif and sans-serif web-safe font stack](http://forum.koohii.com/post-224795.html#pid224795) on the forum.

On the backend a php helper outputs kanji like this:

```html
<span class="cj-k" lang="ja" xml:lang="ja">一</span>
```

The font stack is specified via CSS (cj-s and cj-t are remnants of the Chinese version, simplified & traditional):

```css
.cj-k { font-family:"Hiragino Mincho Pro", "ヒラギノ明朝 Pro W3", "ＭＳ 明朝", "ＭＳ Ｐ明朝", serif; }
.cj-s { font-family:"Kaiti", "STKaiti", "Kai", "AR PL UKai CN", "Microsoft YaHei", "Heiti SC", sans-serif; }
.cj-t { font-family:"TW-Kai", "TW-Moe-Std-Kai", "DFKai-SB", "BiauKai", "AR PL UKai TW", "Microsoft JhengHei", "Heiti TC", serif; }
```
